# Generated by sdks/python/generate.py from the 'check-report' root of `onebudgetspec schema`.
# Do not edit: re-run the generator. Each docstring is the schema's description verbatim.
# ruff: noqa: D200, D205, D212, D400, D415, E501

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType

Direction = TypeAliasType("Direction", Literal["max", "min"])
"""
Which side of the threshold is within.
"""


class Host(BaseModel):
    """
    The host conditions recorded beside a result.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    conditions: dict[str, str]
    """
    Each condition the file declares, and for a `reported` result each condition its
    command returned, by name.
    """
    cpus: int = Field(..., ge=0)
    """
    The CPUs available to this process.
    """
    load1: float | None
    """
    The 1-minute load average; null where unreadable.
    """
    mem_available_mib: int | None = Field(..., ge=0)
    """
    Available memory in MiB; null where unreadable.
    """


Verdict = TypeAliasType("Verdict", Literal["within", "over", "error"])
"""
A result's verdict.
"""


class CheckResult(BaseModel):
    """
    One budget's measurement.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    actual: float | None
    """
    The measured value; null on an error.
    """
    detail: str | None
    """
    The `detail` a `reported` command wrote; null when it wrote none.
    """
    direction: Direction
    """
    The budget's direction.
    """
    ended_at: AwareDatetime
    """
    When the measurement ended (RFC 3339), never before `started_at`.
    """
    error: str | None
    """
    Why the measurement failed; null unless `verdict` is `error`.
    """
    file: str
    """
    The budgets file's path, as discovered or given.
    """
    headroom: float | None
    """
    `threshold - actual` under `max`, `actual - threshold` under `min`; negative when
    over, null on an error.
    """
    headroom_percent: float | None
    """
    `headroom / threshold * 100`; null on an error or when the threshold is 0.
    """
    host: Host
    """
    The host conditions recorded beside this result.
    """
    id: str
    """
    The budget's id.
    """
    labels: list[str]
    """
    The budget's labels, empty when it has none.
    """
    started_at: AwareDatetime
    """
    When the measurement started (RFC 3339).
    """
    threshold: float
    """
    The budget's threshold.
    """
    unit: str
    """
    The budget's unit.
    """
    verdict: Verdict
    """
    `within`, `over` or `error`.
    """


class CheckReport(BaseModel):
    """
    What `check` answers with: one result per selected budget, in measurement order.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    results: list[CheckResult]
    """
    One result per selected budget.
    """
    schema_version: Literal[1]
    """
    Always `1`.
    """
