# Generated by sdks/python/generate.py from the 'list-report' root of `onebudgetspec schema`.
# Do not edit: re-run the generator. Each docstring is the schema's description verbatim.
# ruff: noqa: D200, D205, D212, D400, D415, E501

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType

Direction = TypeAliasType("Direction", Literal["max", "min"])
"""
Which side of the threshold is within.
"""


Measure = TypeAliasType("Measure", Literal["elapsed", "reported"])
"""
How a budget's value is measured.
"""


class ListedBudget(BaseModel):
    """
    One budget as `list` reports it: every field the file gives, plus the file.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    command: list[str]
    """
    The argv that measures it.
    """
    description: str | None
    """
    The budget's description; null when it has none.
    """
    direction: Direction
    """
    The budget's direction.
    """
    file: str
    """
    The budgets file's path, as discovered or given.
    """
    id: str
    """
    The budget's id.
    """
    labels: list[str]
    """
    The budget's labels, empty when it has none.
    """
    measure: Measure
    """
    How the value is measured.
    """
    threshold: float
    """
    The budget's threshold.
    """
    timeout_seconds: int | None = Field(..., ge=0)
    """
    The budget's timeout; null when it has none.
    """
    unit: str
    """
    The budget's unit.
    """


class ListReport(BaseModel):
    """
    What `list` answers with: the selected budgets, in file order.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    budgets: list[ListedBudget]
    """
    The selected budgets.
    """
    schema_version: Literal[1]
    """
    Always `1`.
    """
