"""Generate the SDK's report models from the binary's own ``onebudgetspec schema``.

``python generate.py`` writes ``src/onebudgetspec_sdk/_generated``; ``python generate.py
--check`` writes nothing and fails, naming each file, when what is committed differs from
what the current schema generates. The binary is ``ONEBUDGETSPEC_BIN`` when set, else the
workspace's ``target/debug/onebudgetspec``.
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
GENERATED = HERE / "src" / "onebudgetspec_sdk" / "_generated"
WORKSPACE_BINARY = HERE.parents[1] / "target" / "debug" / "onebudgetspec"
#: The bundle roots the SDK's calls return, and the module each is generated into.
ROOTS = {"check-report": "check_report.py", "list-report": "list_report.py"}
HEADER = (
    "# Generated by sdks/python/generate.py from the {root!r} root of `onebudgetspec schema`.\n"
    "# Do not edit: re-run the generator. Each docstring is the schema's description verbatim.\n"
    "# ruff: noqa: D200, D205, D212, D400, D415, E501"
)


class GenerateError(Exception):
    """A step of generation failed; the message says which and what to do."""


def _run(command: list[str], *, stdin: str | None = None) -> str:
    try:
        completed = subprocess.run(
            command, input=stdin, capture_output=True, text=True, check=False
        )
    except OSError as error:
        raise GenerateError(f"cannot run {command[0]}: {error}") from error
    if completed.returncode != 0:
        raise GenerateError(
            f"{' '.join(command)} exited {completed.returncode}:\n{completed.stderr.strip()}"
        )
    return completed.stdout


def bundle() -> dict[str, object]:
    """The schema bundle the binary prints."""
    binary = os.environ.get("ONEBUDGETSPEC_BIN") or str(WORKSPACE_BINARY)
    if not Path(binary).is_file():
        raise GenerateError(
            f"{binary} is missing; build it with `cargo build -p onebudgetspec` "
            "or point ONEBUDGETSPEC_BIN at one"
        )
    return json.loads(_run([binary, "schema"]))


def _ruff() -> str:
    ruff = shutil.which("ruff")
    if ruff is None:
        raise GenerateError("ruff is not on PATH; run the generator with `uv run python ...`")
    return ruff


def render(root: str, schema: object) -> str:
    """One root's module: datamodel-codegen's models, formatted as the package is."""
    with tempfile.TemporaryDirectory() as scratch:
        source = Path(scratch) / f"{root}.json"
        output = Path(scratch) / "models.py"
        source.write_text(json.dumps(schema))
        _run(
            [
                sys.executable,
                "-W",
                "ignore",
                "-m",
                "datamodel_code_generator",
                "--input",
                str(source),
                "--input-file-type",
                "jsonschema",
                "--output",
                str(output),
                "--output-model-type",
                "pydantic_v2.BaseModel",
                "--target-python-version",
                "3.11",
                "--use-type-alias",
                "--enum-field-as-literal",
                "all",
                "--use-standard-collections",
                "--use-union-operator",
                "--field-constraints",
                "--strict-nullable",
                "--use-title-as-name",
                "--use-schema-description",
                "--use-field-description",
                "--use-double-quotes",
                "--disable-timestamp",
                "--formatters",
                "builtin",
                "--custom-file-header",
                HEADER.format(root=root),
            ]
        )
        text = output.read_text()
    config = ["--config", str(HERE / "pyproject.toml")]
    text = _run(
        [_ruff(), "check", *config, "--fix-only", "--quiet", "--stdin-filename", "m.py", "-"],
        stdin=text,
    )
    return _run([_ruff(), "format", *config, "--stdin-filename", "m.py", "-"], stdin=text)


def files(schema_bundle: dict[str, object]) -> dict[str, str]:
    """Every generated file's name and content."""
    roots = schema_bundle["roots"]
    if not isinstance(roots, dict):
        raise GenerateError("the schema bundle has no `roots` object")
    version = schema_bundle["version"]
    generated = {
        "__init__.py": (
            '"""Models generated from `onebudgetspec schema`; see sdks/python/generate.py."""\n'
            "\n"
            "#: The version of the schema bundle these models were generated from.\n"
            f"SCHEMA_BUNDLE_VERSION = {version!r}\n"
        )
    }
    for root, module in ROOTS.items():
        generated[module] = render(root, roots[root])
    return generated


def main(argv: list[str] | None = None) -> int:
    """Write the generated files, or with ``--check`` compare them; returns the exit status."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="compare; write nothing")
    arguments = parser.parse_args(argv)
    try:
        wanted = files(bundle())
    except GenerateError as error:
        print(f"generate: {error}", file=sys.stderr)
        return 1
    stale = sorted(
        name
        for name, content in wanted.items()
        if not (GENERATED / name).is_file() or (GENERATED / name).read_text() != content
    )
    extra = sorted(path.name for path in GENERATED.glob("*.py") if path.name not in wanted)
    if arguments.check:
        for name in [*stale, *extra]:
            print(
                f"generate: src/onebudgetspec_sdk/_generated/{name} differs from what "
                "`onebudgetspec schema` generates; run 'uv run python generate.py' in sdks/python",
                file=sys.stderr,
            )
        return 1 if stale or extra else 0
    GENERATED.mkdir(parents=True, exist_ok=True)
    for name in stale:
        (GENERATED / name).write_text(wanted[name])
    for name in extra:
        (GENERATED / name).unlink()
    return 0


if __name__ == "__main__":
    sys.exit(main())
